//
//  OCIApplication.m
//  ocimages
//
//  Created by Uli Kusterer on 29.07.17.
//  Copyright © 2017 Uli Kusterer. All rights reserved.
//

#import "OCIApplication.h"

@implementation OCIApplication

-(NSString*) stringAsIdentifier: (NSString*)keyString
{
	NSCharacterSet * nonIdentCS = [[NSCharacterSet characterSetWithCharactersInString: @"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz01234567890_"] invertedSet];
	NSMutableString * identString = [keyString mutableCopy];
	NSRange foundRange = { 0, 0 };
	while ((foundRange = [identString rangeOfCharacterFromSet: nonIdentCS]).location != NSNotFound) {
		[identString replaceCharactersInRange: foundRange withString: @"_"];
	}
	while ((foundRange = [identString rangeOfString: @"__"]).location != NSNotFound) {
		[identString replaceCharactersInRange: foundRange withString: @"_"];
	}
	while ([identString rangeOfCharacterFromSet: [NSCharacterSet decimalDigitCharacterSet]].location == 0) { // Naughty! Identifiers may not start with a number!
		[identString replaceCharactersInRange: NSMakeRange(0, 1) withString: @"_"];
	}
	return identString;
}


-(NSString*) quotedString: (NSString*)inStr
{
	NSMutableString * quotedString = [inStr mutableCopy];
	[quotedString replaceOccurrencesOfString: @"\\" withString: @"\\\\" options:0 range: (NSRange){0,quotedString.length}];
	[quotedString replaceOccurrencesOfString: @"\"" withString: @"\\\"" options:0 range: (NSRange){0,quotedString.length}];
	[quotedString replaceOccurrencesOfString: @"\r" withString: @"\\r" options:0 range: (NSRange){0,quotedString.length}];
	[quotedString replaceOccurrencesOfString: @"\n" withString: @"\\n" options:0 range: (NSRange){0,quotedString.length}];
	[quotedString insertString: @"\"" atIndex: 0];
	[quotedString insertString: @"\"" atIndex: quotedString.length];
	return quotedString;
}


-(NSDictionary<NSString*,id>*) templateNamed: (NSString*)inTemplateName
{
	if (!inTemplateName)
		inTemplateName = @"swift";
	static NSDictionary<NSString*,NSDictionary<NSString*,id>*>* sTemplates = nil;
	if (!sTemplates) {
		sTemplates = @{
					   @"objective-c": @{
							   @"source-filename-suffix": @".m",
							   @"header-filename-suffix": @".h",
							   @"header-prelude": @"// This file was auto-generated by ocimages from the catalog %1$@. Do not edit it,\n// instead, edit the catalog and run ocimages on it again.\n\n#import <Foundation/Foundation.h>\n\n",
							   @"source-prelude": @"// This file was auto-generated by ocimages from the catalog %1$@. Do not edit it,\n// instead, edit the catalog and run ocimages on it again.\n\n#import \"%2$@.h\"\n\n",
							   @"header-postlude": @"",
							   @"source-postlude": @"",
							   @"header-constant": @"extern NSString * const %1$@%2$@;\n",
							   @"source-constant": @"NSString * const %1$@%2$@ = @%3$@;\n"
							   },
					   @"swift": @{
							   @"source-filename-suffix": @".swift",
							   @"source-prelude": @"// This file was auto-generated by ocimages from the catalog %1$@. Do not edit it,\n// instead, edit the catalog and run ocimages on it again.\n\nimport Foundation\n\nstruct %2$@ {\n",
							   @"source-postlude": @"}\n",
							   @"source-constant": @"    static let %2$@ = %3$@ // %1$@\n"
							   }
					   };
	}
	return sTemplates[inTemplateName.lowercaseString];
}


-(BOOL) openFile:(NSString *)filePath
{
	NSString * lang = [[NSUserDefaults standardUserDefaults] objectForKey: @"-language"];
	NSDictionary<NSString*,id>* template = [self templateNamed: lang];
	if (!template) {
		NSLog(@"Unknown language: %@", lang);
		return NO;
	}
	
	NSString * classPrefix = [[NSUserDefaults standardUserDefaults] objectForKey: @"-class-prefix"];
	if (!classPrefix) {
		classPrefix = @"";
	}

	NSString * catalogName = [classPrefix stringByAppendingString: filePath.lastPathComponent.stringByDeletingPathExtension];
	NSArray<NSString*>* fileTypes = @[ @"png", @"tiff", @"pdf", @"imageset", @"appiconset" ];
	NSMutableSet * files = [NSMutableSet set];
	NSDirectoryEnumerator * enny = [[NSFileManager defaultManager] enumeratorAtPath: filePath];
	if (!enny) {
		NSLog( @"Couldn't enumerate asset catalog/directory: %@", filePath );
		return NO;
	}
	
	for (NSString* currPath = enny.nextObject; currPath != nil; currPath = enny.nextObject) {
		if ([fileTypes containsObject: currPath.pathExtension.lowercaseString] ) {
			NSString * baseName = currPath.lastPathComponent.stringByDeletingPathExtension;
			if (![baseName hasSuffix: @"@2x"] && ![baseName hasSuffix: @"@3x"]) {
				[files addObject: baseName];
				[enny skipDescendants];	// Some of our supported formats are folders/packages.
			}
		}
	}
	
	NSString * headerSuffix = template[@"header-filename-suffix"];
	NSMutableString * sourceFileContents = [NSMutableString string];
	NSMutableString * headerFileContents = headerSuffix ? [NSMutableString string] : nil;
	
	[headerFileContents appendFormat: template[@"header-prelude"], filePath.lastPathComponent, catalogName];
	[sourceFileContents appendFormat: template[@"source-prelude"], filePath.lastPathComponent, catalogName];
	
	for (NSString * imageName in files) {
		NSString * identName = [self stringAsIdentifier: imageName];
		[headerFileContents appendFormat: template[@"header-constant"], catalogName, identName];
		[sourceFileContents appendFormat: template[@"source-constant"], catalogName, identName, [self quotedString: imageName]];
	}

	[headerFileContents appendString: template[@"header-postlude"]];
	[sourceFileContents appendString: template[@"source-postlude"]];

	NSError * err = nil;
	if (headerSuffix && ![headerFileContents writeToFile: [catalogName stringByAppendingString: headerSuffix] atomically: YES encoding: NSUTF8StringEncoding error: &err]) {
		NSLog(@"Can't write header: %@", err);
		return NO;
	}
	if (![sourceFileContents writeToFile: [catalogName stringByAppendingString: template[@"source-filename-suffix"]] atomically: YES encoding: NSUTF8StringEncoding error: &err]) {
		NSLog(@"Can't write source code: %@", err);
		return NO;
	}
	
	return YES;
}

@end
